version = 1

[handlers.file]
class = "logging.handlers.RotatingFileHandler"
level = "INFO"
filename = "/opt/pi-log/logs/pi-log.log"
maxBytes = 1048576
backupCount = 5
formatter = "standard"

[formatters.standard]
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

[loggers.app]
level = "INFO"
handlers = ["file"]
propagate = false

[loggers.root]
level = "INFO"
handlers = ["file"]
