[loggers]
keys = ["root", "pi_log"]

[handlers]
keys = ["console", "file"]

[formatters]
keys = ["standard"]

[logger_root]
level = "INFO"
handlers = ["console"]

[logger_pi_log]
level = "INFO"
handlers = ["console", "file"]
qualname = "pi-log"
propagate = false

[handler_console]
class = "logging.StreamHandler"
level = "INFO"
formatter = "standard"
args = "(sys.stdout,)"

[handler_file]
class = "logging.handlers.RotatingFileHandler"
level = "INFO"
formatter = "standard"
args = "('/opt/pi-log/logs/pi-log.log', 'a', 1048576, 5)"

[formatter_standard]
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"
